/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminUI;


import UI.jLoginPanel;
import javax.swing.JPanel;
import info5100.university.example.Department.Department;
import java.awt.CardLayout;
import java.awt.Component;




public class AdminDB extends javax.swing.JPanel {

    /**
     * Creates new form AdminInfo
     */
    
    JPanel mainWorkArea;
    Department department;
    
    public AdminDB(JPanel mainWorkArea, Department d) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.department = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCourseDetail = new javax.swing.JButton();
        btnOverview = new javax.swing.JButton();
        btnStuInfo = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnCourseDetail1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        controlPanel.setBackground(new java.awt.Color(51, 51, 51));

        btnCourseDetail.setBackground(new java.awt.Color(51, 51, 51));
        btnCourseDetail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCourseDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseDetail.setText("Faculty");
        btnCourseDetail.setToolTipText("Click to view Course Rankings");
        btnCourseDetail.setBorderPainted(false);
        btnCourseDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCourseDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseDetailActionPerformed(evt);
            }
        });

        btnOverview.setBackground(new java.awt.Color(51, 51, 51));
        btnOverview.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnOverview.setForeground(new java.awt.Color(255, 255, 255));
        btnOverview.setText("Overview");
        btnOverview.setToolTipText("Click to view analysis");
        btnOverview.setBorderPainted(false);
        btnOverview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverviewActionPerformed(evt);
            }
        });

        btnStuInfo.setBackground(new java.awt.Color(51, 51, 51));
        btnStuInfo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnStuInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnStuInfo.setText("Student information");
        btnStuInfo.setToolTipText("Click to view Details of all students");
        btnStuInfo.setBorderPainted(false);
        btnStuInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuInfoActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(51, 51, 51));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setToolTipText("Click to view Course Rankings");
        btnLogOut.setBorderPainted(false);
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnCourseDetail1.setBackground(new java.awt.Color(51, 51, 51));
        btnCourseDetail1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCourseDetail1.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseDetail1.setText("Statistics");
        btnCourseDetail1.setToolTipText("Click to view Course Rankings");
        btnCourseDetail1.setBorderPainted(false);
        btnCourseDetail1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCourseDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseDetail1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCourseDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(btnOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnStuInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnCourseDetail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnStuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCourseDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCourseDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 0, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AdminDashBoard");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 355, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuInfoActionPerformed
        // TODO add your handling code here:
        Details createstudentPanel = new Details(department);
        splitPane.setRightComponent(createstudentPanel);
    }//GEN-LAST:event_btnStuInfoActionPerformed

    private void btnOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverviewActionPerformed
        // TODO add your handling code here:
        AdminOverview overpanel = new AdminOverview(department);
        splitPane.setRightComponent(overpanel);
    }//GEN-LAST:event_btnOverviewActionPerformed

    private void btnCourseDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseDetailActionPerformed
        // TODO add your handling code here:
        Details2 coursedetails = new Details2(department);
        splitPane.setRightComponent(coursedetails);
    }//GEN-LAST:event_btnCourseDetailActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[0];
        jLoginPanel loginPanel = (jLoginPanel) component;
        loginPanel.populateRoleCombo();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCourseDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseDetail1ActionPerformed
       
       FeedbackCourses fdbk = new FeedbackCourses(department);
        splitPane.setRightComponent(fdbk);  
        
        
    }//GEN-LAST:event_btnCourseDetail1ActionPerformed


    @Override
    public String toString(){
        return "Admin";
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseDetail;
    private javax.swing.JButton btnCourseDetail1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOverview;
    private javax.swing.JButton btnStuInfo;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
