/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminUI;


import UI.jLoginPanel;
import javax.swing.JPanel;
import info5100.university.example.Department.Department;
import java.awt.CardLayout;
import java.awt.Component;




public class AdminDB extends javax.swing.JPanel {

    /**
     * Creates new form AdminInfo
     */
    
    JPanel mainWorkArea;
    Department department;
    
    public AdminDB(JPanel mainWorkArea, Department d) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.department = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCourseDetail = new javax.swing.JButton();
        btnOverview = new javax.swing.JButton();
        btnStuInfo = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        btnCourseDetail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCourseDetail.setText("Course Rankings");
        btnCourseDetail.setToolTipText("Click to view Course Rankings");
        btnCourseDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCourseDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseDetailActionPerformed(evt);
            }
        });

        btnOverview.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnOverview.setText("Overview");
        btnOverview.setToolTipText("Click to view analysis");
        btnOverview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverviewActionPerformed(evt);
            }
        });

        btnStuInfo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnStuInfo.setText("Student information");
        btnStuInfo.setToolTipText("Click to view Details of all students");
        btnStuInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuInfoActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setToolTipText("Click to view Course Rankings");
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCourseDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStuInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCourseDetail, btnLogOut, btnOverview, btnStuInfo});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnStuInfo)
                .addGap(18, 18, 18)
                .addComponent(btnOverview)
                .addGap(13, 13, 13)
                .addComponent(btnCourseDetail)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuInfoActionPerformed
        // TODO add your handling code here:
        Details createstudentPanel = new Details(department);
        splitPane.setRightComponent(createstudentPanel);
    }//GEN-LAST:event_btnStuInfoActionPerformed

    private void btnOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverviewActionPerformed
        // TODO add your handling code here:
        AdminOverview overpanel = new AdminOverview(department);
        splitPane.setRightComponent(overpanel);
    }//GEN-LAST:event_btnOverviewActionPerformed

    private void btnCourseDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseDetailActionPerformed
        // TODO add your handling code here:
        Details coursedetails = new Details(department);
        splitPane.setRightComponent(coursedetails);
    }//GEN-LAST:event_btnCourseDetailActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[0];
        jLoginPanel loginPanel = (jLoginPanel) component;
        loginPanel.populateRoleCombo();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
        
    }//GEN-LAST:event_btnLogOutActionPerformed


    @Override
    public String toString(){
        return "Admin";
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseDetail;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOverview;
    private javax.swing.JButton btnStuInfo;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
