/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminUI;


import StudentUI.StudentEmployment;
import UI.jLoginPanel;
import UICommons.ScreenChanger;
import UICommons.WorkArea;
import info5100.university.example.Department.Department;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 
 */
public class FeedbackCourses extends javax.swing.JPanel implements ScreenChanger {

    /**
     * Creates new form CourseRankings
     */
    
        
    Department department;
    WorkArea workArea;
    public FeedbackCourses(WorkArea workArea, Department d) {
        initComponents();        
        this.workArea = workArea;
        //txtcourse.setVisible(false);
        lblcourse.setVisible(false);
        jScrollPane1.setVisible(false);
        this.department = d;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCriteria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        cmbCriteria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbCriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Top Salaries", "Promotions", "Employer Rankings" }));
        cmbCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCriteriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Select Criteria for Course Ranking :");

        lblcourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcourse.setForeground(new java.awt.Color(255, 51, 51));
        lblcourse.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblcourse.setText("Courses :");

        jLabel3.setBackground(new java.awt.Color(204, 0, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Course Feedback");
        jLabel3.setOpaque(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(lblcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnLogout)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCriteriaActionPerformed
        // TODO add your handling code here:
        updateCourseRanking();
        
    }//GEN-LAST:event_cmbCriteriaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            // TODO add your handling code here:
            //        mainWorkArea.remove(this);
            //        Component[] componentArray = mainWorkArea.getComponents();
            //        Component component = componentArray[0];
            //        mainWorkArea.remove(componentArray[componentArray.length - 1]);
            //        jLoginPanel loginPanel = (jLoginPanel) component;
            //        try {
            //            loginPanel.populateRoleCombo();
            //        } catch (IOException ex) {
            //            Logger.getLogger(StudentEmployment.class.getName()).log(Level.SEVERE, null, ex);
            //        }
            //
            //        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            //        layout.previous(mainWorkArea);

            nextScreen(workArea, new jLoginPanel(workArea, department), "jLoginPanel");
        } catch (IOException ex) {
            Logger.getLogger(FeedbackCourses.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> cmbCriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblcourse;
    // End of variables declaration//GEN-END:variables

    private void updateCourseRanking() {
        if (cmbCriteria.getSelectedItem() == "Top Salaries") {
            lblcourse.setVisible(true);
            jScrollPane1.setVisible(true);
            jTextArea1.setLineWrap(true);
           jTextArea1.setText(department.getCoursesByMostSalaryPaidinDepartment().toString());
        } else if (cmbCriteria.getSelectedItem() == "Promotions") {
          jScrollPane1.setVisible(true);
            lblcourse.setVisible(true);
            jTextArea1.setLineWrap(true);
           jTextArea1.setText(department.getPopularCoursesByJobPromotion().toString());
        } else if (cmbCriteria.getSelectedItem() == "Employer Rankings") {
            jScrollPane1.setVisible(true);
            lblcourse.setVisible(true);
            jTextArea1.setLineWrap(true);
          jTextArea1.setText(department.getPopularCoursesByOrganizationRanking().toString());
        }
        else{
            lblcourse.setVisible(false);
            jScrollPane1.setVisible(false);
        }
    }
}
