package UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import StudentUI.StudentDetail;
import java.awt.CardLayout;
import javax.swing.JPanel;

import info5100.university.example.Department.Department;
import info5100.university.example.Persona.StudentProfile;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

import UICommons.ScreenChanger;
import UICommons.WorkArea;


/**
 *
 * * @author Ankur Bywar
 */
public class jLoginPanel extends javax.swing.JPanel implements ScreenChanger {

    /**
     * Creates new form LoginScreen
     */
    WorkArea workArea;
    Department department;
    StudentProfile selectedID = null;

    public jLoginPanel(WorkArea workArea, Department d) throws IOException {
        initComponents();

        this.workArea = workArea;
        this.department = d;
        lblStudentID.setVisible(false);
        txtStudentID.setVisible(false);
        populateRoleCombo();
        displayPersonImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRole = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox<>();
        lblStudentID = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        warningForValidId = new javax.swing.JLabel();
        imgLogo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        lblRole.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Choose Roles");

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student", "Faculty" }));
        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });

        lblStudentID.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblStudentID.setText("Enter Student Id");

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        imgLogo1.setBackground(new java.awt.Color(255, 0, 0));
        imgLogo1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        imgLogo1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(warningForValidId)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentID))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStudentID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnLogin)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRole)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningForValidId)
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        JPanel selectedPanel = (JPanel) cmbRoles.getSelectedItem();

        if (selectedPanel.getClass() == StudentDetail.class) {
            selectedID = department.getStudentDirectory().findStudent(txtStudentID.getText());
            if (selectedID != null) {
                warningForValidId.setText("");
                try {
                    selectedPanel = new StudentDetail(workArea, department, selectedID);
                } catch (IOException ex) {
                    Logger.getLogger(jLoginPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtStudentID.setText("");
            } else {
                txtStudentID.setText("");
                warningForValidId.setText("Please enter valid student Id");
                
            }
        } else if (selectedPanel.getClass() == AdminUI.AdminDB.class) {
            warningForValidId.setText("");
            try {
                selectedPanel = new AdminUI.AdminDB(workArea, department );
            } catch (IOException ex) {
                Logger.getLogger(jLoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        nextScreen(workArea, selectedPanel, "selectedPanel");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
        updateRolesVisibility();
    }//GEN-LAST:event_cmbRolesActionPerformed

    public void populateRoleCombo() throws IOException {

        cmbRoles.removeAllItems();
        AdminUI.AdminDB admin = new AdminUI.AdminDB(workArea, department);
       StudentDetail student = new StudentDetail(workArea, department, selectedID);

        cmbRoles.addItem(admin);
        cmbRoles.addItem(student);

    }

    public void populateStudentBox() {

        lblStudentID.setText("Enter Student ID");
        txtStudentID.setVisible(true);

    }

    private void updateRolesVisibility() {
        
        warningForValidId.setText("");
        if ((cmbRoles.getSelectedItem() == null) || (cmbRoles.getSelectedItem().getClass() == AdminUI.AdminDB.class)) {
            selectedID = null;
            lblStudentID.setVisible(false);
            txtStudentID.setVisible(false);
            return;
        } else {
            lblStudentID.setVisible(true);
            lblStudentID.setText("Enter Student ID");
            txtStudentID.setVisible(true);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<Object> cmbRoles;
    private javax.swing.JLabel imgLogo1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JLabel warningForValidId;
    // End of variables declaration//GEN-END:variables

    private void displayPersonImage() throws IOException {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        File imageFile = new File("/Users/mrs.katey/Downloads/NEULOGO.png");
            BufferedImage img = ImageIO.read(imageFile);
            Image scaled = img.getScaledInstance(1000, 100, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaled);
            imgLogo1.setIcon(icon);
        
    }
}
