/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentUI;

import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.Department.Department;
import info5100.university.example.Employer.EmployerProfile;
import info5100.university.example.Persona.EmploymentHistory.EmploymentHistory;
import info5100.university.example.Persona.EmploymentHistory.Employment;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UI.jLoginPanel;
import UICommons.WorkArea;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import UICommons.ScreenChanger;

/**
 *
 ** @author Ankur Bywar
 */
public class StudentEmployment extends javax.swing.JPanel implements ScreenChanger {

    /**
     * Creates new form AddEmployment
     */
    EmploymentHistory employment;
    StudentProfile studentdetails;
    Department department;
    EmploymentHistory jobhistory;
    List<CourseOffer> list;
    
    WorkArea workArea;

    public StudentEmployment(WorkArea workArea, StudentProfile studentdata, Department d) {
        initComponents();
        this.workArea = workArea;
        this.studentdetails = studentdata;
        this.department = d;
        this.studentdetails = studentdata;
        this.employment = studentdetails.getEmploymenthistory();

        this.list = studentdata.getTranscript().getCourses();
        JPanel panel = new JPanel();
        co1.setText(list.get(0).getCourseName());
        co2.setText(list.get(1).getCourseName());
        co3.setText(list.get(2).getCourseName());
        co4.setText(list.get(3).getCourseName());
        co5.setText(list.get(4).getCourseName());
        co6.setText(list.get(5).getCourseName());
        co7.setText(list.get(6).getCourseName());
        co8.setText(list.get(7).getCourseName());
        

        panel.add(co1);
        panel.add(co2);
        panel.add(co3);
        panel.add(co4);
        panel.add(co5);
        panel.add(co6);
        panel.add(co7);
        panel.add(co8);
        this.add(panel);

    }

//    AddEmployment(JPanel mainWorkArea, StudentProfile studentdata, Department d) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddEmp = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        txtJobPosition = new javax.swing.JTextField();
        lblSalary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        lblRanking = new javax.swing.JLabel();
        txtCompanyRanking = new javax.swing.JTextField();
        lblSubject = new javax.swing.JLabel();
        co1 = new javax.swing.JCheckBox();
        co2 = new javax.swing.JCheckBox();
        co3 = new javax.swing.JCheckBox();
        co4 = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        co5 = new javax.swing.JCheckBox();
        co7 = new javax.swing.JCheckBox();
        co6 = new javax.swing.JCheckBox();
        co8 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        lblAddEmp.setBackground(new java.awt.Color(204, 0, 51));
        lblAddEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddEmp.setText("Add Employment Details");

        lblCompany.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompany.setText("Company");

        lblPosition.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosition.setText("Job Title");

        lblSalary.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalary.setText("Salary");

        lblRanking.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRanking.setText("Rank your Compnay");

        lblSubject.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(51, 51, 255));
        lblSubject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubject.setText("Choose the Relevant Subjects Taken");

        co1.setForeground(new java.awt.Color(255, 51, 51));
        co1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co1ActionPerformed(evt);
            }
        });

        co2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        co2.setForeground(new java.awt.Color(255, 51, 51));

        co3.setForeground(new java.awt.Color(255, 51, 51));

        co4.setForeground(new java.awt.Color(255, 51, 51));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Submit");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        co5.setForeground(new java.awt.Color(255, 51, 51));

        co7.setForeground(new java.awt.Color(255, 51, 51));

        co6.setBackground(new java.awt.Color(255, 51, 51));
        co6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co6ActionPerformed(evt);
            }
        });

        co8.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("/5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJobPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(txtCompanyRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(co7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(co2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(co5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(co6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(co8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(co1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(co3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(co4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogout)
                            .addComponent(btnSave))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 513, Short.MAX_VALUE)
                .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addComponent(lblAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCompany)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalary))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJobPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosition))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompanyRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(co1)
                            .addComponent(co5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(co7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(co2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(co6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(co8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(co3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(co4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void co1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_co1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        ArrayList<CourseOffer> courseList = new ArrayList<>();
        if (co1.isSelected()) {
            courseList.add(list.get(0));
        }
        if (co2.isSelected()) {
            courseList.add(list.get(1));
        }
        if (co3.isSelected()) {
            courseList.add(list.get(2));
        }
        if (co4.isSelected()) {
            courseList.add(list.get(3));
        }
        if (co5.isSelected()) {
            courseList.add(list.get(4));
        }
        if (co6.isSelected()) {
            courseList.add(list.get(5));
        }
        if (co7.isSelected()) {
            courseList.add(list.get(6));
        }
        if (co8.isSelected()) {
            courseList.add(list.get(7));
        }
        
        Double sal = 0d;
        try{
             sal= Double.parseDouble(txtSalary.getText());
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(this, "Please enter salary in proper format");
             return;
        }
        
        int rank = 0;
        try{
             rank = Integer.parseInt(txtCompanyRanking.getText());
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(this, "Please enter ranking in proper format");
             return;
        }
        studentdetails.getEmploymenthistory().getEmployments().add(new Employment(courseList, txtJobPosition.getText(), sal, new EmployerProfile(txtCompanyName.getText(), rank)));
        JOptionPane.showMessageDialog(this, "Job Detail Information Saved");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
//        mainWorkArea.remove(this);
//        Component[] componentArray = mainWorkArea.getComponents();
//        Component component = componentArray[0];
//        mainWorkArea.remove(componentArray[componentArray.length - 1]);
//        jLoginPanel loginPanel = (jLoginPanel) component;
//        try {
//            loginPanel.populateRoleCombo();
//        } catch (IOException ex) {
//            Logger.getLogger(StudentEmployment.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
//        layout.previous(mainWorkArea);
     nextScreen(workArea, new ViewStudentEmplyment (workArea, department), "jLoginPanel");

//nextScreen(workArea, new StudentDetail(workArea, department), "StudentDetail");


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void co6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_co6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox co1;
    private javax.swing.JCheckBox co2;
    private javax.swing.JCheckBox co3;
    private javax.swing.JCheckBox co4;
    private javax.swing.JCheckBox co5;
    private javax.swing.JCheckBox co6;
    private javax.swing.JCheckBox co7;
    private javax.swing.JCheckBox co8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddEmp;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCompanyRanking;
    private javax.swing.JTextField txtJobPosition;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
