/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentUI;


import AdminUI.FeedbackCourses;
import UI.jLoginPanel;
import UICommons.ScreenChanger;
import UICommons.WorkArea;
import javax.swing.JPanel;

import java.awt.CardLayout;

import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.EmploymentHistory.EmploymentHistory;
import info5100.university.example.Persona.StudentProfile;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *

 */
public class StudentDetail extends javax.swing.JPanel implements ScreenChanger {

    /**
     * Creates new form StudentInfo
     */
    WorkArea workArea;
    StudentProfile studentdetails;
    Department department;
    EmploymentHistory info;

    public StudentDetail() {

    }

    public StudentDetail(WorkArea workArea, Department d, StudentProfile studentdetail) throws IOException {

        initComponents();

        this.workArea = workArea;
        this.department = d;
        this.studentdetails = studentdetail;
        //tblStudent.getTableHeader.setFont(new Font("SEGOE UI") Font.BOLD,12);
        
        

        if (studentdetail != null) {
            this.info = studentdetail.getEmploymenthistory();
            populateTable();
             displayPersonImage();

        }

    }

    StudentDetail(WorkArea workArea, Department department) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        lblGPA = new javax.swing.JLabel();
        AddJobDetails = new javax.swing.JButton();
        lblStudentName = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        btnViewEmployment = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        txtGPA = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        tblStudent.setBackground(new java.awt.Color(204, 204, 204));
        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Course1", null, null, null},
                {"Course2", null, null, null},
                {"Course3", null, null, null},
                {"Course4", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Index", "Course Number", "Course Name", "Score"
            }
        ));
        tblStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblStudent.setEnabled(false);
        tblStudent.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblStudent.setRowHeight(25);
        tblStudent.setSelectionBackground(new java.awt.Color(255, 57, 95));
        tblStudent.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tblStudentComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(tblStudent);
        if (tblStudent.getColumnModel().getColumnCount() > 0) {
            tblStudent.getColumnModel().getColumn(0).setResizable(false);
            tblStudent.getColumnModel().getColumn(0).setHeaderValue("Index");
            tblStudent.getColumnModel().getColumn(1).setHeaderValue("Course Number");
            tblStudent.getColumnModel().getColumn(2).setHeaderValue("Course Name");
            tblStudent.getColumnModel().getColumn(3).setHeaderValue("Score");
        }

        lblGPA.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblGPA.setForeground(new java.awt.Color(255, 255, 255));
        lblGPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPA.setText("Total GPA");

        AddJobDetails.setBackground(new java.awt.Color(0, 0, 0));
        AddJobDetails.setForeground(new java.awt.Color(255, 255, 255));
        AddJobDetails.setText("Add Jop Description");
        AddJobDetails.setPreferredSize(new java.awt.Dimension(103, 29));
        AddJobDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJobDetailsActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 0, 51));
        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentName.setText("WELCOME ");

        studentName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        studentName.setForeground(new java.awt.Color(255, 255, 255));
        studentName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnViewEmployment.setBackground(new java.awt.Color(0, 0, 0));
        btnViewEmployment.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEmployment.setText("View Job Details");
        btnViewEmployment.setPreferredSize(new java.awt.Dimension(103, 29));
        btnViewEmployment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmploymentActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setPreferredSize(new java.awt.Dimension(103, 29));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        btnfeedback.setBackground(new java.awt.Color(0, 0, 0));
        btnfeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnfeedback.setText("Feedback");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        imgLogo.setText("<<no IMage>>");

        txtGPA.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtGPA.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(lblGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddJobDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViewEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnfeedback)
                                .addGap(27, 27, 27)
                                .addComponent(AddJobDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnViewEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGPA)
                            .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(272, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddJobDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJobDetailsActionPerformed
        // TODO add your handling code here:

        StudentEmployment emp = new StudentEmployment(workArea, studentdetails, department);
        workArea.getMainWorkArea().add("WordAreaPanel", emp);
        CardLayout layout = (CardLayout) workArea.getMainWorkArea().getLayout();
        layout.next(workArea.getMainWorkArea());


    }//GEN-LAST:event_AddJobDetailsActionPerformed

    private void tblStudentComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblStudentComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStudentComponentAdded

    private void btnViewEmploymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmploymentActionPerformed
        // TODO add your handling code here:
//        ViewStudentEmplyment employ = new ViewStudentEmplyment(workArea, studentdetails, department);
//        workArea.add("WordAreaPanel", employ);
//        CardLayout layout = (CardLayout) workArea.getLayout();
//        layout.next(workArea);


         nextScreen(workArea, new ViewStudentEmplyment(workArea, studentdetails, department), "FeedbackCourses");

    }//GEN-LAST:event_btnViewEmploymentActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        try {
            // TODO add your handling code here:
//        workArea.remove(this);
//        Component[] componentArray = workArea.getComponents();
//        Component component = componentArray[0];
//        jLoginPanel loginPanel = (jLoginPanel) component;
//        try {
//            loginPanel.populateRoleCombo();
//        } catch (IOException ex) {
//            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        CardLayout layout = (CardLayout) workArea.getLayout();
//        layout.previous(workArea);


            nextScreen(workArea, new jLoginPanel(workArea, department), "jLoginPanel");
        } catch (IOException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }


        
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
       Feedback feedback = null;
        try {
            feedback = new Feedback(workArea, department,studentdetails);
        } catch (IOException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
//        workArea.add("feedbackpanel", feedback);
//        CardLayout layout = (CardLayout) workArea.getLayout();
//        layout.next(workArea);


        nextScreen(workArea, feedback, "jLoginPanel");

    }//GEN-LAST:event_btnfeedbackActionPerformed

    public void populateTable() {
        studentName.setText(studentdetails.getPerson().getName());
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
        model.setRowCount(0);
        List<SeatAssignment> list = studentdetails.getTranscript().getSeatAssignments();
        int num = 0;

        for (SeatAssignment co : list) {

            Object[] row = new Object[4];
            row[0] = num + 1;
            row[1] = co.getSeat().getCourseoffer().getCourseNumber();
            row[2] = co.getSeat().getCourseoffer().getCourseName();
            row[3] = String.format("%.1f", co.getGrade());

            model.addRow(row);
            num++;
        }
        txtGPA.setText(String.format("%.1f", studentdetails.getTranscript().calculateGPA()));

    }

    @Override
    public String toString() {
        return "Student";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJobDetails;
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnViewEmployment;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel studentName;
    private javax.swing.JTable tblStudent;
    private javax.swing.JLabel txtGPA;
    // End of variables declaration//GEN-END:variables

    private void displayPersonImage() throws IOException {
         File imageFile = new File("/Users/mrs.katey/Downloads/defaultPersonLogo.png");
          
            BufferedImage img = ImageIO.read(imageFile);
            Image scaled = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaled);
            imgLogo.setIcon(icon);
        }
    
}
