/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentUI;

import UI.jLoginPanel;
import UICommons.ScreenChanger;
import UICommons.WorkArea;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.EmploymentHistory.Employment;
import info5100.university.example.Persona.EmploymentHistory.EmploymentHistory;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *

 */
public class ViewStudentEmplyment extends javax.swing.JPanel implements ScreenChanger {

    /**
     * Creates new form ViewEmployment
     */
    EmploymentHistory employ;
    StudentProfile studentdetails;
    Department department;
    EmploymentHistory info;
    
    WorkArea workArea;
    

    public ViewStudentEmplyment(WorkArea workArea, StudentProfile studentdata, Department d) {
        initComponents();
        this.workArea = workArea;
        this.studentdetails = studentdata;
        this.department = d;
        try {
            displayPersonImage();
        } catch (IOException ex) {
            Logger.getLogger(ViewStudentEmplyment.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (studentdata != null && d != null) {
            this.info = studentdata.getEmploymenthistory();
            populateTable();
        }

    }

    ViewStudentEmplyment(WorkArea workArea, Department department) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblView = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        imgLogo4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        lblView.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblView.setForeground(new java.awt.Color(255, 51, 51));
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("View Employment Data");

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        tblEmp.setBackground(new java.awt.Color(204, 204, 204));
        tblEmp.setForeground(new java.awt.Color(102, 102, 102));
        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Company", "Job Title", "Salary", "Company Ranking", "Relevant Courses"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmp.setEnabled(false);
        jScrollPane1.setViewportView(tblEmp);
        if (tblEmp.getColumnModel().getColumnCount() > 0) {
            tblEmp.getColumnModel().getColumn(2).setPreferredWidth(5);
            tblEmp.getColumnModel().getColumn(3).setResizable(false);
            tblEmp.getColumnModel().getColumn(3).setPreferredWidth(2);
        }

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(imgLogo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            // TODO add your handling code here:
//        mainWorkArea.remove(this);
//        Component[] componentArray = mainWorkArea.getComponents();
//        mainWorkArea.remove(componentArray[componentArray.length - 1]);
//        Component component = componentArray[0];
//        jLoginPanel loginPanel = (jLoginPanel) component;
//        try {
//            loginPanel.populateRoleCombo();
//        } catch (IOException ex) {
//            Logger.getLogger(ViewStudentEmplyment.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
//        layout.previous(mainWorkArea);


            nextScreen(workArea, new jLoginPanel(workArea, department), "jLoginPanel");
        } catch (IOException ex) {
            Logger.getLogger(ViewStudentEmplyment.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblEmp.getModel();
        model.setRowCount(0);

        for (Employment vs : info.getEmployments()) {

            Object[] row = new Object[5];
            row[0] = vs.getEmployer().getName();
            row[1] = vs.getJobposition();
            row[2] = vs.getSalary();
            row[3] = vs.getEmployer().getRanking();
            row[4] = vs.getRelevantCourses();
            model.addRow(row);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel imgLogo4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblView;
    private javax.swing.JTable tblEmp;
    // End of variables declaration//GEN-END:variables

    private void displayPersonImage() throws IOException {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         File imageFile = new File("/Users/mrs.katey/Downloads/NEULOGO.png");
            BufferedImage img = ImageIO.read(imageFile);
            Image scaled = img.getScaledInstance(1000, 100, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaled);
            imgLogo4.setIcon(icon);
    
    
    }
}
